{"name": "【关键字驱动】登录测试：login_fail", "status": "passed", "description": "\n一个函数覆盖所有登录场景（成功、失败等）。\n", "attachments": [{"name": "Response for login_fail", "source": "fe3f3dfb-46ac-48c2-8c8a-3809ecf865c0-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "7f61f891-c518-4ae0-b53b-07d4b667a769-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "285e2ebc-59bb-4fcf-90a9-25a0592cfb18-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case_id", "value": "'login_fail'"}, {"name": "request_data", "value": "{'username': 'baduser', 'password': 'wrongpwd'}"}, {"name": "expected_results", "value": "{'status': 'fail', 'token_present': False, 'errno': 700, 'errmsg': '账号不存在'}"}], "start": 1758509569754, "stop": 1758509569826, "uuid": "fb3820d4-5c67-420f-a750-38bce94d9fec", "historyId": "96b85e47354916d82cae9935e7601da7", "testCaseId": "685f2740a62874ca5f595fc8a245e463", "fullName": "tests.test_api.test_cases.TestAuth#test_login_scenarios", "labels": [{"name": "story", "value": "User Login"}, {"name": "feature", "value": "Authentication"}, {"name": "parentSuite", "value": "tests.test_api"}, {"name": "suite", "value": "test_cases"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "LAPTOP-JKP7AV64"}, {"name": "thread", "value": "13376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api.test_cases"}], "titlePath": ["tests", "test_api", "test_cases.py", "TestAuth"]}