{"name": "Test login failure - invalid credential", "status": "passed", "attachments": [{"name": "Login Fail Response", "source": "3a73503b-b356-4981-acb4-439cef9f265d-attachment.txt", "type": "text/plain"}, {"name": "log", "source": "cd61867a-2a59-45c1-b841-b1d7fe28eaea-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "3036ae40-7611-448c-aa66-fff4f5084d59-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "dabd588d-bb50-4431-8168-4b73a040f555-attachment.txt", "type": "text/plain"}], "start": 1758262683711, "stop": 1758262683775, "uuid": "79494ea2-b2f0-4eb0-a685-b4b399556a36", "historyId": "a88b13b0669e0e260b051d914016a682", "testCaseId": "a88b13b0669e0e260b051d914016a682", "fullName": "tests.test_cases.TestAuth#test_login_fail", "labels": [{"name": "feature", "value": "Authentication"}, {"name": "story", "value": "User Login"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cases"}, {"name": "subSuite", "value": "TestAuth"}, {"name": "host", "value": "LAPTOP-JKP7AV64"}, {"name": "thread", "value": "9964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cases"}], "titlePath": ["tests", "test_cases.py", "TestAuth"]}